resources:
  - ../../base

namespace: dev

# patchesStrategicMerge:
  # - backend-deployment-patch.yaml
  # - backend-service-patch.yaml
  # - frontend-deployment-patch.yaml
  # - frontend-service-patch.yaml
# add dev label to all resources
commonLabels:
  env: dev

# define latest images to be used in this env
images:
  - name: trnproj1.azurecr.io/backend@sha256
    newName: amr158/argocd-demo-backend
    # newTag: 0.0.0
    newTag: 0.1.0
  - name: trnproj1.azurecr.io/frontend@sha256
    newName: amr158/argocd-demo-frontend
    newTag: 0.4.0
