resources:
  - ../../base/apps
  # - env.yaml

namespace: dev

configMapGenerator:
  - name: env
    behavior: replace
    literals:
      - domain=dev.aam.com

# patchesStrategicMerge:
#   - frontend-deployment-patch.yaml
  # - backend-deployment-patch.yaml
  # - backend-service-patch.yaml
  # - frontend-service-patch.yaml
# add dev label to all resources
commonLabels:
  env: dev

# define latest images to be used in this env
images:
  - name: trnproj1.azurecr.io/backend@sha256
    # newName: amr158/argocd-demo-backend
    newName: dockre/argocd-demo-backend
    newTag: 0.0.1
    # newTag: 0.0.0
    # newName: mcr.microsoft.com/dotnet/samples
    # newTag: aspnetapp
  - name: trnproj1.azurecr.io/frontend@sha256
    newName: amr158/argocd-demo-frontend
    newTag: 0.4.0


replacements:
  - source:
      kind: ConfigMap
      name: env
      fieldPath: data.domain
    targets:
      - select:
          kind: Ingress
          labelSelector: 'type=app'
        fieldPaths:
          - spec.rules.*.host
        options:
          delimiter: '.' 
          index: 10
      - select:
          kind: Ingress
          labelSelector: 'type=api'
        fieldPaths:
          - spec.rules.*.host



# patches:
#   - target:
#       kind: Ingress
#       group: api
#       # annotations.type: api
#     patch: |-
#       - op: add
#         path: /spec/rules/0/host
#         value: 'dev.aam.localhost'





# patchesStrategicMerge:
# - ingress-patch.yaml

# patchesJson6902:
